#ifndef LEVEL_H
#define LEVEL_H

#define TARGET_SCREEN_TILE_WIDTH 32
#define TARGET_SCREEN_TILE_HEIGHT 24
#define TARGET_SCREEN_TILE_OFFSET_X 4
#define TARGET_SCREEN_TILE_OFFSET_Y 1
#define TARGET_SCREEN_BLOCK_WIDTH (TARGET_SCREEN_TILE_WIDTH / 2)
#define TARGET_SCREEN_BLOCK_HEIGHT (TARGET_SCREEN_TILE_HEIGHT / 2)

#define OBSTACLE_BLOCK 219
#define OBSTACLE_BLOCK_COLOR COLOR_WHITE

#define PICKUP_BLOCK 219
#define PICKUP_BLOCK_COLOR COLOR_YELLOW

void LoadLevel(void);

#endif
