#ifndef PUZL_MSX_COLOR_H
#define PUZL_MSX_COLOR_H

#include <msx/msx.h>

#define COLOR_BLACK MSX_COLOR_BLACK
#define COLOR_WHITE MSX_COLOR_WHITE
#define COLOR_RED MSX_COLOR_DARK_RED
#define COLOR_CYAN MSX_COLOR_SKY_BLUE
#define COLOR_PURPLE MSX_COLOR_PURPLE
#define COLOR_GREEN MSX_COLOR_DARK_GREEN
#define COLOR_BLUE MSX_COLOR_DARK_BLUE
#define COLOR_YELLOW MSX_COLOR_LIGHT_YELLOW
#define COLOR_ORANGE MSX_COLOR_YELLOW
#define COLOR_BROWN MSX_COLOR_RED
#define COLOR_LIGHT_RED MSX_COLOR_BRIGHT_RED
#define COLOR_GREY_1 MSX_COLOR_GREY // NOTE: Duplicate.
#define COLOR_GREY_2 MSX_COLOR_GREY // NOTE: Duplicate.
#define COLOR_LIGHT_GREEN MSX_COLOR_LIGHT_GREEN
#define COLOR_LIGHT_BLUE MSX_COLOR_LIGHT_BLUE
#define COLOR_GREY_3 MSX_COLOR_GREY // NOTE: Duplicate.

#define NUMBER_OF_COLORS 16

#endif
