#
PROJECT_NAME := tjld

TARGET := web

SDIR := ./src
PUZLDIR := $(SDIR)/puzl
BDIR := ./bin/$(TARGET)

SRC := $(wildcard $(SDIR)/*.c)
SRC += $(wildcard $(PUZLDIR)/sdl/*.c)

OBJ := $(wildcard $(BDIR)/*.o)
OBJS := $(patsubst $(SRC)/%.c,$(BDIR)/%.o,$(SRC))

CFLAGS := -s USE_SDL=2 -I $(PUZLDIR)
LFLAGS := 

HTML := $(PROJECT_NAME).html
EXE := $(BDIR)/$(HTML)
########################################

.SUFFIXES:
.PHONY: all
all: $(EXE)

$(EXE): $(OBJS) | $(BDIR)
	emcc $^ -o $@ $(CFLAGS) $(LFLAGS)

$(BDIR)/%.o: $(SDIR)/%.c $(SDIR)/$(PUZLDIR)/%.c | $(BDIR)
	emcc -c $< -o $@ $(CFLAGS) $(LFLAGS)

$(BDIR):
  $(MKDIR) $@

.PHONY: clean
clean:
	@rm -rf $(BDIR)/*

# NOTE: $(BDIR) path must exist prior to running this script.
# TODO: Create $(BDIR) if it does not exist.
